// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package version

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/go-logr/logr"
	"github.com/spf13/afero"
	apimachineryversion "k8s.io/apimachinery/pkg/version"
	componentbaseversion "k8s.io/component-base/version"

	"github.com/gardener/gardener-landscape-kit/componentvector"
	configv1alpha1 "github.com/gardener/gardener-landscape-kit/pkg/apis/config/v1alpha1"
	utilscomponentvector "github.com/gardener/gardener-landscape-kit/pkg/utils/componentvector"
	"github.com/gardener/gardener-landscape-kit/pkg/utils/files"
)

const (
	// MetaDirName is the name of the metadata directory within .glk
	MetaDirName = "meta"
	// VersionFileName is the name of the version metadata file
	VersionFileName = "version.json"
)

var (
	//go:embed VERSION
	fallbackVersion string

	version apimachineryversion.Info
)

func init() {
	version = componentbaseversion.Get()

	// Set the fallback version if unset, i.e. it was not passed via ld flags.
	if strings.HasPrefix(version.GitVersion, "v0.0.0") {
		version.GitVersion = strings.TrimSpace(fallbackVersion)
	}
}

// Info contains version information for a generated base
type Info struct {
	Version    string `json:"version"`
	GitVersion string `json:"gitVersion"`
	GitCommit  string `json:"gitCommit"`
	BuildDate  string `json:"buildDate"`
	Major      string `json:"major"`
	Minor      string `json:"minor"`
}

// WriteVersionMetadata writes the current version information to .glk/meta/version.json
func WriteVersionMetadata(targetPath string, fs afero.Afero) error {
	metadata := Info{
		Version:    version.GitVersion,
		GitVersion: version.GitVersion,
		GitCommit:  version.GitCommit,
		BuildDate:  version.BuildDate,
		Major:      version.Major,
		Minor:      version.Minor,
	}

	metaDir := filepath.Join(targetPath, files.GLKSystemDirName, MetaDirName)
	if err := fs.MkdirAll(metaDir, 0744); err != nil {
		return fmt.Errorf("failed to create metadata directory: %w", err)
	}

	data, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal version metadata: %w", err)
	}

	versionFilePath := filepath.Join(metaDir, VersionFileName)
	if err := fs.WriteFile(versionFilePath, data, 0644); err != nil {
		return fmt.Errorf("failed to write version metadata: %w", err)
	}

	return nil
}

// ReadVersionMetadata reads the version information from .glk/meta/version.json
func ReadVersionMetadata(targetPath string, fs afero.Afero) (*Info, error) {
	versionFilePath := filepath.Join(targetPath, files.GLKSystemDirName, MetaDirName, VersionFileName)

	exists, err := fs.Exists(versionFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to check version file existence: %w", err)
	}

	if !exists {
		return nil, fmt.Errorf("base directory was generated by an older version of gardener-landscape-kit that did not track version information. Please regenerate the base directory with the current version")
	}

	data, err := fs.ReadFile(versionFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read version metadata: %w", err)
	}

	var metadata Info
	if err := json.Unmarshal(data, &metadata); err != nil {
		return nil, fmt.Errorf("failed to parse version metadata: %w", err)
	}

	return &metadata, nil
}

// ValidateVersionCompatibility checks if the landscape version is compatible with the base version.
// Returns an error if landscapeVersion > baseVersion.
func ValidateVersionCompatibility(baseVersion, landscapeVersion string) error {
	baseVer, err := semver.NewVersion(baseVersion)
	if err != nil {
		return fmt.Errorf("failed to parse base version %q: %w", baseVersion, err)
	}

	landscapeVer, err := semver.NewVersion(landscapeVersion)
	if err != nil {
		return fmt.Errorf("failed to parse landscape version %q: %w", landscapeVersion, err)
	}

	// Allow landscape generation if landscapeVersion <= baseVersion
	if landscapeVer.GreaterThan(baseVer) {
		return fmt.Errorf("landscape generation version (%s) is newer than base generation version (%s). Please regenerate the base directory using the current version of gardener-landscape-kit, or downgrade your gardener-landscape-kit installation to %s or earlier", landscapeVersion, baseVersion, baseVersion)
	}

	return nil
}

// ValidateLandscapeVersionCompatibility performs end-to-end version compatibility validation
// by reading the base version from metadata and comparing it with the current tool version.
func ValidateLandscapeVersionCompatibility(targetPath string, fs afero.Afero) error {
	baseMetadata, err := ReadVersionMetadata(targetPath, fs)
	if err != nil {
		return err
	}

	return ValidateVersionCompatibility(baseMetadata.Version, version.GitVersion)
}

// CheckGLKComponentVersion validates that the tool version matches the gardener-landscape-kit
// component version in the component vector.
// The behavior depends on the checkMode in the configuration:
// - If checkMode is "Strict" (or nil/default), returns an error on mismatch.
// - If checkMode is "Warning", logs a warning on mismatch and returns nil.
func CheckGLKComponentVersion(cv utilscomponentvector.Interface, config *configv1alpha1.LandscapeKitConfiguration, log logr.Logger) error {
	toolVersion := version.GitVersion
	componentVersion, found := cv.FindComponentVersion(componentvector.NameGardenerGardenerLandscapeKit)

	if !found {
		return fmt.Errorf("gardener-landscape-kit component not found in component vector - this should not happen as it's part of the default component vector")
	}

	if toolVersion != componentVersion {
		// Determine the check mode (default to Strict)
		checkMode := configv1alpha1.VersionCheckModeStrict
		if config != nil && config.VersionConfig != nil && config.VersionConfig.CheckMode != nil {
			checkMode = *config.VersionConfig.CheckMode
		}

		if checkMode == configv1alpha1.VersionCheckModeWarning {
			log.Info("WARNING: version mismatch - tool version does not match gardener-landscape-kit component version in component vector - obtain the matching gardener-landscape-kit version or adjust the component vector", "toolVersion", toolVersion, "componentVersion", componentVersion)
			return nil
		}

		return fmt.Errorf("version mismatch: tool version (%s) does not match gardener-landscape-kit component version (%s) in component vector - obtain the matching gardener-landscape-kit version or adjust the component vector", toolVersion, componentVersion)
	}

	return nil
}

// Get returns the version of GLK.
func Get() apimachineryversion.Info {
	return version
}
