//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&LandscapeKitConfiguration{}, func(obj interface{}) { SetObjectDefaults_LandscapeKitConfiguration(obj.(*LandscapeKitConfiguration)) })
	return nil
}

func SetObjectDefaults_LandscapeKitConfiguration(in *LandscapeKitConfiguration) {
	SetDefaults_LandscapeKitConfiguration(in)
	if in.OCM != nil {
		SetDefaults_OCMConfig(in.OCM)
	}
	if in.Repositories != nil {
		if in.Repositories.Base != nil {
			SetDefaults_BaseRepositoryConfig(in.Repositories.Base)
		}
		if in.Repositories.Landscape != nil {
			SetDefaults_LandscapeRepositoryConfig(in.Repositories.Landscape)
		}
	}
}
