//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseRepositoryConfig) DeepCopyInto(out *BaseRepositoryConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseRepositoryConfig.
func (in *BaseRepositoryConfig) DeepCopy() *BaseRepositoryConfig {
	if in == nil {
		return nil
	}
	out := new(BaseRepositoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsConfiguration) DeepCopyInto(out *ComponentsConfiguration) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsConfiguration.
func (in *ComponentsConfiguration) DeepCopy() *ComponentsConfiguration {
	if in == nil {
		return nil
	}
	out := new(ComponentsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositoryRef) DeepCopyInto(out *GitRepositoryRef) {
	*out = *in
	if in.Branch != nil {
		in, out := &in.Branch, &out.Branch
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.Commit != nil {
		in, out := &in.Commit, &out.Commit
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositoryRef.
func (in *GitRepositoryRef) DeepCopy() *GitRepositoryRef {
	if in == nil {
		return nil
	}
	out := new(GitRepositoryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeKitConfiguration) DeepCopyInto(out *LandscapeKitConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = new(RepositoriesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(ComponentsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.VersionConfig != nil {
		in, out := &in.VersionConfig, &out.VersionConfig
		*out = new(VersionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MergeMode != nil {
		in, out := &in.MergeMode, &out.MergeMode
		*out = new(MergeMode)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeKitConfiguration.
func (in *LandscapeKitConfiguration) DeepCopy() *LandscapeKitConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscapeKitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscapeKitConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeRepositoryConfig) DeepCopyInto(out *LandscapeRepositoryConfig) {
	*out = *in
	in.Ref.DeepCopyInto(&out.Ref)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeRepositoryConfig.
func (in *LandscapeRepositoryConfig) DeepCopy() *LandscapeRepositoryConfig {
	if in == nil {
		return nil
	}
	out := new(LandscapeRepositoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMComponent) DeepCopyInto(out *OCMComponent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMComponent.
func (in *OCMComponent) DeepCopy() *OCMComponent {
	if in == nil {
		return nil
	}
	out := new(OCMComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMConfig) DeepCopyInto(out *OCMConfig) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.RootComponent = in.RootComponent
	if in.IgnoreMissingComponents != nil {
		in, out := &in.IgnoreMissingComponents, &out.IgnoreMissingComponents
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMConfig.
func (in *OCMConfig) DeepCopy() *OCMConfig {
	if in == nil {
		return nil
	}
	out := new(OCMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoriesConfig) DeepCopyInto(out *RepositoriesConfig) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(BaseRepositoryConfig)
		**out = **in
	}
	if in.Landscape != nil {
		in, out := &in.Landscape, &out.Landscape
		*out = new(LandscapeRepositoryConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoriesConfig.
func (in *RepositoriesConfig) DeepCopy() *RepositoriesConfig {
	if in == nil {
		return nil
	}
	out := new(RepositoriesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionConfiguration) DeepCopyInto(out *VersionConfiguration) {
	*out = *in
	if in.DefaultVersionsUpdateStrategy != nil {
		in, out := &in.DefaultVersionsUpdateStrategy, &out.DefaultVersionsUpdateStrategy
		*out = new(DefaultVersionsUpdateStrategy)
		**out = **in
	}
	if in.CheckMode != nil {
		in, out := &in.CheckMode, &out.CheckMode
		*out = new(VersionCheckMode)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionConfiguration.
func (in *VersionConfiguration) DeepCopy() *VersionConfiguration {
	if in == nil {
		return nil
	}
	out := new(VersionConfiguration)
	in.DeepCopyInto(out)
	return out
}
