builds:
- id: gardener-landscape-kit
  main: ./cmd/gardener-landscape-kit
  ldflags:
  - -X k8s.io/component-base/version.gitMajor={{.Env.MAJOR_VERSION}}
  - -X k8s.io/component-base/version.gitMinor={{.Env.MINOR_VERSION}}
  - -X k8s.io/component-base/version.gitVersion={{.Env.VERSION}}
  - -X k8s.io/component-base/version.gitTreeState={{.Git.TreeState}}
  - -X k8s.io/component-base/version.gitCommit={{.Git.FullCommit}}
  - -X k8s.io/component-base/version.buildDate={{.Date}}
  - -X k8s.io/component-base/version/verflag.programName=gardener-landscape-kit
