apiVersion: landscape.config.gardener.cloud/v1alpha1
kind: LandscapeKitConfiguration
# ocm:
#   repositories:
#   - <repo-url>
#   rootComponent:
#     name: <component-name>
#     version: <component-version>
#   originalRefs: true
repositories:
  landscape:
    url: http://gitops:testtest@git.local.gardener.cloud:6080/gitops/test-landscape.git
    ref:
      branch: main
    baseLink: ./base
# components:
#   exclude:
#   - component-name
