// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-componentname-constants.sh. DO NOT EDIT.

package componentvector

const (
	// NameGardenerGardener is a constant for a component in the component vector with name 'github.com/gardener/gardener'.
	NameGardenerGardener = "github.com/gardener/gardener"
	// NameGardenerGardenerExtensionNetworkingCalico is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-networking-calico'.
	NameGardenerGardenerExtensionNetworkingCalico = "github.com/gardener/gardener-extension-networking-calico"
	// NameGardenerGardenerExtensionNetworkingCilium is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-networking-cilium'.
	NameGardenerGardenerExtensionNetworkingCilium = "github.com/gardener/gardener-extension-networking-cilium"
	// NameGardenerGardenerExtensionOsGardenlinux is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-os-gardenlinux'.
	NameGardenerGardenerExtensionOsGardenlinux = "github.com/gardener/gardener-extension-os-gardenlinux"
	// NameGardenerGardenerExtensionOsSuseChost is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-os-suse-chost'.
	NameGardenerGardenerExtensionOsSuseChost = "github.com/gardener/gardener-extension-os-suse-chost"
	// NameGardenerGardenerExtensionProviderAlicloud is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-alicloud'.
	NameGardenerGardenerExtensionProviderAlicloud = "github.com/gardener/gardener-extension-provider-alicloud"
	// NameGardenerGardenerExtensionProviderAws is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-aws'.
	NameGardenerGardenerExtensionProviderAws = "github.com/gardener/gardener-extension-provider-aws"
	// NameGardenerGardenerExtensionProviderAzure is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-azure'.
	NameGardenerGardenerExtensionProviderAzure = "github.com/gardener/gardener-extension-provider-azure"
	// NameGardenerGardenerExtensionProviderGcp is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-gcp'.
	NameGardenerGardenerExtensionProviderGcp = "github.com/gardener/gardener-extension-provider-gcp"
	// NameGardenerGardenerExtensionProviderOpenstack is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-openstack'.
	NameGardenerGardenerExtensionProviderOpenstack = "github.com/gardener/gardener-extension-provider-openstack"
	// NameGardenerGardenerExtensionRuntimeGvisor is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-runtime-gvisor'.
	NameGardenerGardenerExtensionRuntimeGvisor = "github.com/gardener/gardener-extension-runtime-gvisor"
	// NameGardenerGardenerExtensionShootCertService is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-shoot-cert-service'.
	NameGardenerGardenerExtensionShootCertService = "github.com/gardener/gardener-extension-shoot-cert-service"
	// NameGardenerGardenerExtensionShootDnsService is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-shoot-dns-service'.
	NameGardenerGardenerExtensionShootDnsService = "github.com/gardener/gardener-extension-shoot-dns-service"
	// NameGardenerGardenerExtensionShootNetworkingProblemdetector is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-shoot-networking-problemdetector'.
	NameGardenerGardenerExtensionShootNetworkingProblemdetector = "github.com/gardener/gardener-extension-shoot-networking-problemdetector"
	// NameGardenerGardenerExtensionShootOidcService is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-shoot-oidc-service'.
	NameGardenerGardenerExtensionShootOidcService = "github.com/gardener/gardener-extension-shoot-oidc-service"
	// NameGardenerGardenerLandscapeKit is a constant for a component in the component vector with name 'github.com/gardener/gardener-landscape-kit'.
	NameGardenerGardenerLandscapeKit = "github.com/gardener/gardener-landscape-kit"
)
