# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

services:
  forgejo:
    container_name: glk-forgejo
    image: codeberg.org/forgejo/forgejo:15.0.3
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD-SHELL", "test -f /runner/config.yaml" ]
      interval: 10s
      retries: 5
      start_period: 2s
      timeout: 10s
    ports:
    - "6080:6080"
    volumes:
    - ./forgejo.conf:/app.ini.sample:ro
    - ./runner-config.yaml:/runner-config.yaml:ro
    - ../../dev/git-server/data:/data
    - ../../dev/git-server/runner:/runner
    - ./entrypoint.sh:/entrypoint.sh:ro
    restart: unless-stopped
    networks:
      default:
        aliases:
        - git.local.gardener.cloud

  docker-in-docker:
    container_name: glk-forgejo-dind
    image: data.forgejo.org/oci/docker:dind
    command: ['--insecure-registry=glk-registry.local.gardener.cloud:6001']
    hostname: docker  # Must set hostname as TLS certificates are only valid for docker or localhost
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_HOST: docker-in-docker
    volumes:
    - ../../dev/git-server/docker_certs:/certs
    restart: unless-stopped

  runner:
    container_name: glk-forgejo-runner
    image: data.forgejo.org/forgejo/runner:12.10.2
    command: >-
      forgejo-runner --config /runner/config.yaml daemon
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
    - ../../dev/git-server/runner:/runner
    - ../../dev/git-server/docker_certs:/certs
    restart: unless-stopped
    depends_on:
      forgejo:
        condition: service_healthy
      docker-in-docker:
        condition: service_started

networks:
  default:
    external: true
    name: kind
