name: Build

on:
  workflow_call:
    inputs:
      release-version:
        type: string
        default: set-prerelease
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@v1
    with:
      mode: ${{ inputs.mode }}
      version-operation: ${{ inputs.release-version }}
      version-commit-callback-action-path: .github/actions/prepare-release
    permissions:
      id-token: write

  build-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.capture.outputs.date }}
    steps:
      - id: capture
        run: echo "date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

  tests:
    permissions:
      contents: read
    runs-on: ${{ github.repository_owner == 'gardener' && 'ubuntu-latest-large' || 'ubuntu-latest' }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@v1
      - uses: gardener/cc-utils/.github/actions/setup-git-identity@v1
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: run-verify
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p /tmp/blobs.d
          make verify-extended |& tee /tmp/blobs.d/verify-log.txt
          tar czf /tmp/blobs.d/gosec-report.tar.gz gosec-report.sarif
          tar czf /tmp/blobs.d/verify-log.tar.gz -C /tmp/blobs.d verify-log.txt
      - name: add-tests-report-to-component-descriptor
        uses: gardener/cc-utils/.github/actions/export-ocm-fragments@v1
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            - name: gosec-report
              relation: local
              access:
                type: localBlob
                localReference: gosec-report.tar.gz
              labels:
              - name: gardener.cloud/purposes
                value:
                - lint
                - sast
                - gosec
              - name: gardener.cloud/comment
                value: |
                  we use gosec (linter) for SAST scans
                  see: https://github.com/securego/gosec
            - name: test-results
              relation: local
              access:
                type: localBlob
                localReference: verify-log.tar.gz
              labels:
              - name: gardener.cloud/purposes
                value:
                - test

  gardener-landscape-kit:
    permissions:
      contents: read
    needs:
      - prepare
      - tests
      - build-date
    strategy:
      matrix:
        args:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
            archive_suffix: .tar.gz
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            archive_suffix: .tar.gz
          - os: darwin
            arch: amd64
            runner: ubuntu-latest
            archive_suffix: .tar.gz
          - os: darwin
            arch: arm64
            runner: ubuntu-latest
            archive_suffix: .tar.gz
          - os: windows
            arch: amd64
            runner: ubuntu-latest
            archive_suffix: .zip
          - os: windows
            arch: arm64
            runner: ubuntu-latest
            archive_suffix: .zip
    runs-on: ${{ matrix.args.runner }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@v1
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: build-gardener-landscape-kit
        shell: bash
        run: |
          set -euo pipefail

          os=${{ matrix.args.os }}
          arch=${{ matrix.args.arch }}

          if [ ${os} == 'windows' ]; then
            exe_suffix='.exe'
          else
            exe_suffix=''
          fi

          mkdir -p /tmp/blobs.d
          prefix=/tmp/blobs.d/gardener-landscape-kit
          platform_suffix="-${os}-${arch}"
          outpath="${prefix}${platform_suffix}${exe_suffix}"
          archive="${prefix}${platform_suffix}${{ matrix.args.archive_suffix }}.archive"

          GOOS=${os} \
          GOARCH=${arch} \
          BUILD_DATE=${{ needs.build-date.outputs.date }} \
          BUILD_PACKAGES=./cmd/gardener-landscape-kit \
          BUILD_OUTPUT_FILE=${outpath} \
            make build

          echo "built into ${outpath}"

          if ${{ matrix.args.os == 'windows' }}; then
            (
              cd $(dirname ${outpath})
              zip -j ${archive} $(basename ${outpath})
            )
          else
            tar cvzf ${archive} -C /tmp/blobs.d $(basename ${outpath})
          fi

          unlink ${outpath}
      - uses: gardener/cc-utils/.github/actions/export-ocm-fragments@v1
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            name: gardener-landscape-kit
            relation: local
            type: executable
            extraIdentity:
              os: ${{ matrix.args.os }}
              architecture: ${{ matrix.args.arch }}
            access:
              type: localBlob
              localReference: >-
                gardener-landscape-kit-${{ matrix.args.os }}-${{ matrix.args.arch }}${{ matrix.args.archive_suffix }}.archive

  oci-images:
    name: Build OCI-Images
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@v1
    needs:
    - prepare
    - tests
    - build-date
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      name: gardener-landscape-kit
      version: ${{ needs.prepare.outputs.version }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: gardener/gardener-landscape-kit
      oci-platforms: linux/arm64,linux/amd64
      build-args: |
        BUILD_DATE=${{ needs.build-date.outputs.date }}
