name: Test Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    uses: ./.github/workflows/secret-between-jobs.yml
    with:
      oci-auth-username: foo-user
    secrets:
      oci-auth-password: foo-password
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      id-token: write
