name: Secret Between Jobs

on:
  workflow_call:
    inputs:
      oci-auth-username:
        description: 'OCI registry username for authentication (optional)'
        required: false
        type: string

jobs:
  use-secret:
    runs-on: ubuntu-latest
    # Inject the job output as an environment variable for the entire job
    steps:
      - name: Use the secret
        run: |
          echo "User ${GLK_OCI_REG_USERNAME}"
          echo "Password ${GLK_OCI_REG_PASSWORD}"
        env:
          GLK_OCI_REG_USERNAME: ${{ inputs.oci-auth-username }}
          GLK_OCI_REG_PASSWORD: ${{ secrets.oci-auth-password }}
